### ISSUE TITLE
Atributs de fields dinàmics

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/ooui.js#18]

**Comment by mguellsegarra** [comment]
Pel parseig, es pot veure el codi vigent a:
https://gist.github.com/ecarreras/520221bd118d84b99448d4e8c1e1a521

**Comment by mguellsegarra** [comment]
@ecarreras 

He implementat una primera versió del parseig i aplicació dels atributs. Ja és vigent al webclient.

## ooui.js

- El parseig potser és una mica rudimentari, però crec que amb els casos que m'he anat trobant és suficient. El pots veure [aquí](https://github.com/gisce/ooui.js/blob/master/src/helpers/attributeParser.ts).

- La única complicació ha estat amb els camps booleans, que pot ser que arribin com a `0`, `1`, `True` o `False`. He hagut de fer algunes transformacions, però en principi no hi veig més història.

- He fet una bateria de tests amb varis casos reals que he trobat dels diferents forms amb els que he fet proves, [aquí](https://github.com/gisce/ooui.js/blob/master/src/spec/attributeParser.spec.ts). Pel que he anat veient, no he vist casos més complexes que aquests, no sé si se't acut algun valor de `attrs` que sigui molt diferent en estructura o contingut dels que he provat.

## react-ooui

- Pel que fa al `react-ooui`, he reestructurat el component `Form` per a que al detectar canvis en els camps, s'avaluï de nou, se'n treguin els atributs que corresponguin en funció dels valors i cada widget s'actualitzi com pertoca amb el nou estat.

- Aquí la única complicació que he vist, i que potser no arribaria a passar mai, ja que no sé si els atributs es podrien aplicar en funció un camp de text, és el següent:  en els camps de text on l'usuari pot teclejar el valor, l'event de detectar canvis es dispara cada vegada que l'usuari fa una pulsació, amb el que es realenteix tot. Per aquests casos, he implementat un `debounce` de 300 ms per a suavitzar una mica l'experiència. Pels altres camps, booleans, llistes de selecció, etc... l'actualització és instantània.

## Pendent

Quedaria per provar si hi ha atributs que fan referència a camps `One2many`, `Many2one`, `Many2many`. Que es tractés la condició i ho comparés correctament. Però tampoc sé si es fa o té molt de sentit.

**Comment by ecarreras** [comment]
Em sembla tot correcte!

Pels *many normalment no es fan servir per comprovar valors, sinó que el més habitual és que se'ls apliqui un read-only o un invisible.

Bona feina! 💪🏻💪🏻💪🏻
