### ISSUE TITLE
Tenir en compte atribut string en labels

### ISSUE THREAD

**Issue by mguellsegarra** [gisce/ooui.js#22]

**Comment by mguellsegarra** [comment]
Ara ja apareix correctament:

![Screenshot 2021-06-09 at 11 40 30](https://user-images.githubusercontent.com/5711443/121331904-9c618680-c917-11eb-9b70-46b81cf835b0.png)

Abans:
![Screenshot 2021-06-09 at 11 37 13](https://user-images.githubusercontent.com/5711443/121331908-9cfa1d00-c917-11eb-9a91-e76089e33f1b.png)

Vigent al webclient.
@ecarreras @corellian

**Comment by ecarreras** [comment]
Testejat!
